<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../Infraestructura/Pacogroup.Ecommerce.Infrastructure.Interfaces/Pacogroup.Ecommerce.Infrastructure.Interfaces.csproj" />
    <ProjectReference Include="..\Pacogroup.Ecommerce.Domain.Entity\Pacogroup.Ecommerce.Domain.Entity.csproj" />
    <ProjectReference Include="..\Pacogroup.Ecommerce.Domain.Interfaces\Pacogroup.Ecommerce.Domain.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
