<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Permite generar el archivo de documentacion de la API -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Aplicacion/Pacogroup.Ecommerce.Application.DTO/Pacogroup.Ecommerce.Application.DTO.csproj" />
    <ProjectReference Include="../../Aplicacion/Pacogroup.Ecommerce.Application.Interfaces/Pacogroup.Ecommerce.Application.Interfaces.csproj" />
    <ProjectReference Include="../../Aplicacion/Pacogroup.Ecommerce.Application.Main/Pacogroup.Ecommerce.Application.Main.csproj" />
    <ProjectReference Include="../../Dominio/Pacogroup.Ecommerce.Domain.Core/Pacogroup.Ecommerce.Domain.Core.csproj" />
    <ProjectReference Include="../../Infraestructura/Pacogroup.Ecommerce.Infrastructure.Repository/Pacogroup.Ecommerce.Infrastructure.Repository.csproj" />
  </ItemGroup>

</Project>
